### ISSUE TITLE
[Homepage] Radio buttons not linked to the associated title

### ISSUE THREAD

**Issue by pya35** [Orange-OpenSource/Tota11ylost#17]
Radio buttons are not linked to the previous title "Duration"

![Image](https://github.com/user-attachments/assets/8e00f6f9-c39f-4451-851f-19e0df402298)

![Image](https://github.com/user-attachments/assets/b0b17de0-6366-41d5-84c3-0a88a429998c)

**Comment by damiengomez** [comment]
Add to group radio button with a fieldset.

Exemple :
<fieldset>
<legend>Game duration</legend>
  <div>
    <input type="radio" name="gameDuration" id="15min" checked>
    <label for="15min">15 min</label>
  </div>
  <div>
    <input type="radio" name="gameDuration" id="30min" >
    <label for="30min">30 min</label>
  </div>
  […]
</fieldset>
